[Gutenberg] Discover block for Homepage
xwp/wp-travel-theme pull request #19
Opened 2018-04-03 14:29 UTC by miina

Based on #13.

Aims for the following goals:
- [x] Make the heading editable;
- [x] Make the subheading editable;
- [x] Dynamically fetch the latest post from 'posts'.

2018-04-11 03:26 UTC, kienstra requested changes
**Great Work, A Few Small Points Below**

Hi @miina,
Thanks for your Gutenberg expertise here.

As this PR also includes the commits from #13, this review only addresses [the diff](https://github.com/xwp/travel/compare/feature/12-gutenberg_blocks_base...feature/discover_block) between this branch and that branch (feature/12-gutenberg_blocks_base).

Looking at this is probably a lower priority than #13.

2018-04-11 03:26 UTC, kienstra commented on blocks/discover/index.js
> +			if ( 0 === posts.data.length ) {
Could a conditional like `if ( 0 === posts.data.length ) {` wrap the `div.travel-discover-panel` element instead of this entire section? 

It looks like most of the `section.travel-discover` is the same in both cases, and this might be more DRY. But maybe I'm missing a detail.

2018-04-11 03:26 UTC, kienstra commented on includes/class-amp-travel-blocks.php
> +		$output = "<section class='travel-discover py4 mb3 relative xs-hide sm-hide'>
Could you please wrap `$output` in single quotes, and use double quotes for the attributes? But maybe there was a reason for this, I remember seeing a mention of quotes in this repo.

2018-04-11 03:26 UTC, kienstra commented on includes/class-amp-travel-blocks.php
> +		} else {
This isn't a blocker, but the `else` isn't needed.

2018-04-11 03:26 UTC, kienstra commented on includes/class-amp-travel-blocks.php
> +				$excerpt_length = apply_filters( 'excerpt_length', 15 );
Could you please put these comments over the `apply_filters()` lines like in [this example](https://github.com/Automattic/jetpack/blob/master/modules/theme-tools/content-options/blog-display.php#L40) from Jetpack:
```php
/** This filter is documented in wp-includes/formatting.php */
$excerpt_length = apply_filters( 'excerpt_length', 15 );
/** This filter is documented in wp-includes/formatting.php */
$excerpt_more   = apply_filters( 'excerpt_more', ' ...' );
```

2018-04-11 03:26 UTC, kienstra commented on includes/class-amp-travel-blocks.php
> +								<h2 class='travel-discover-heading bold line-height-2 xs-hide sm-hide'>" . esc_attr( $heading ) . "</h2>
Could you please use `esc_html()` instead of `esc_attr()` on this line and the line below?

2018-04-11 03:26 UTC, kienstra commented on includes/class-amp-travel-blocks.php
> +									<a class='travel-link' href=' " . $link . "'>Read more</a>
Could you please call `esc_attr( $link );`

Also, maybe this is just placeholder text. But could you please internationalize `'Read more'`:
```php
esc_html__( 'Read more', 'travel' )
```

2018-04-11 03:26 UTC, kienstra commented on includes/class-amp-travel-blocks.php
> +					<div class='max-width-3 mx-auto px1 md-px2'>
Could you indent this `<section class='travel-discover` line and everything below it one tab to the left (except for the `return $output;` statement).

2018-04-11 03:26 UTC, kienstra commented on assets/css/editor-blocks.css
> +.travel-discover-subheading {
Could you please add an empty line above `.travel-discover-subheading {`

2018-04-12 08:44 UTC, miina commented
@kienstra Thank you for the feedback, made changes accordingly, the block should be ready now, let me know if there's anything else.

2018-04-12 15:38 UTC, miina commented
Note that the texts of the block are static, looks like the texts of dynamic blocks can't be edited directly as with other blocks (at least with the Gutenberg stable version as of current moment) and making the texts editable is something to look into later.

2018-04-12 19:57 UTC, kienstra commented on blocks/discover/index.js
> +			if ( 0 === posts.data.length ) {
Thanks, this [looks good](https://github.com/xwp/travel/pull/19/files/f45b78e7b5a9142a292afa7c6345d29506a42ff0..55e3def40372688420d26fa70cac9c08c8b868af#diff-3215f011460155a7b0e289ca288c19ecR35).

2018-04-12 19:58 UTC, kienstra commented on includes/class-amp-travel-blocks.php
> +		$output = "<section class='travel-discover py4 mb3 relative xs-hide sm-hide'>
Thanks, this [looks good](https://github.com/xwp/travel/pull/19/files/f45b78e7b5a9142a292afa7c6345d29506a42ff0..55e3def40372688420d26fa70cac9c08c8b868af#diff-d85bb5c137cc4b60d13bd558d64a58d9R178).

2018-04-12 20:36 UTC, kienstra approved these changes
**Approved** 

Hi @miina,
Thanks a lot for your work here. This looks good, and it's ready to merge.

As you [mentioned](https://github.com/xwp/travel/pull/19#issuecomment-3808493340) the block's text can't be edited at the moment, as it's a dynamic block.

We might revisit this, but I think it's ready to merge into `develop` now.

<img width="747" alt="discover-not-editable" src="https://user-images.githubusercontent.com/4063887/38703001-b56f47fe-3e67-11e8-9235-9b6b25b88b11.png">

2018-04-12 20:44 UTC, merged