[WIP] Implement PSTT theme
xwp/wp-travel-theme pull request #38
Opened 2018-04-11 08:47 UTC by DavidCramer

Huge work in progress.

- [ ] Implemented the taxonomies and CPT from #33 and #31 into the `./dev` folder.
- [ ] Bring in the custom blocks
- [ ] Configure the build process for the blocks

Fixes #3

2018-04-17 10:29 UTC, DavidCramer commented
@kienstra - could you take a look at this and see if it looks correct according the the task?

2018-04-18 01:53 UTC, kienstra requested changes
**Thanks, Some Points Below**

Hi @DavidCramer,
Thanks for this huge effort. Most of these comments aren't regarding your work, only whether certain elements of the "WP Rig" theme will go along with our theme well.

This is an open discussion, so feel free to reply where you think something is needed.

2018-04-18 01:53 UTC, kienstra commented on comments.php
> +<?php
Thanks for adding this, but we'll probably use the [comments.php](https://github.com/xwp/travel/pull/39/files#diff-3301f48a33589a7bfe66d131714e43d3) from PR #39. That has AMP-specific markup, like `<amp-live-list>`.

2018-04-18 01:53 UTC, kienstra commented on css/comments.css
> +/*--------------------------------------------------------------
This file probably won't be needed.

2018-04-18 01:53 UTC, kienstra commented on css/widgets.css
> +/*--------------------------------------------------------------
This probably isn't needed for now, as I haven't seen widgets in the [design](https://www.figma.com/file/L14jTE7iNGOE7DH57Ro7ncyu/Travel-Theme).

2018-04-18 01:53 UTC, kienstra commented on footer.php
> +<?php
We'll probably use the [footer.php](https://github.com/xwp/travel/pull/39/files#diff-44390cabf006de0249316ec5093ed0c6R1) from #39, as it's very specific to the design.

2018-04-18 01:53 UTC, kienstra commented on header.php
> +<?php
We'll probably use the [header.php](https://github.com/xwp/travel/pull/39/files#diff-1c1ae65fe9828eb6d3cee4edacf90018R1) from #39, as it's also very specific to the designs.

2018-04-18 01:53 UTC, kienstra commented on inc/classes/class-amp-travel-features.php
> + * AMP Travel Theme Features class.
Good idea to rename this, to reflect the fact that it's the "plugin territory" of the theme.

2018-04-18 01:53 UTC, kienstra commented on inc/classes/class-amp-travel-features.php
> +		$this->features = new stdClass();
Thanks for creating `$this->features` to store the instances.

2018-04-18 01:53 UTC, kienstra commented on js/customizer.js
> +	});
Are the 2 `wp.customize()` calls above needed? They seem to be replaced with [Selective Refresh](https://github.com/xwp/travel/pull/38/files#diff-b8746809c04b1698add2a397c385bc9eR19).

2018-04-18 01:53 UTC, kienstra commented on js/navigation.js
> +'use strict';
As I understand it, this is a Native AMP theme, per the [added_theme_support](https://github.com/xwp/travel/blob/c4200803a8407c8db6b25b60fa2f98127adf2ddf/includes/class-amp-travel-theme.php#L73). So we probably don't need any front-end JS files.

2018-04-18 01:53 UTC, kienstra commented on js/skip-link-focus-fix.js
> +'use strict';
Per the [comment above](https://github.com/xwp/travel/pull/38/files#r182256704), I don't think we can use this file.

2018-04-18 01:53 UTC, kienstra commented on phpcs.xml.dist
> +	<file>./dev/</file>
It doesn't look like we have a `./dev` directory, so maybe the `<file>.</file>` line shouldn't change.

2018-04-18 01:53 UTC, kienstra commented on phpcs.xml.dist
> +			<property name="text_domain" type="array" value="travel"/>
It's probably fine to remove 'default' now, but we'll add it again if we translate any strings from native WordPress.

2018-04-18 01:53 UTC, kienstra commented on template-parts/content-search.php
> +<?php
We probably won't need this file. From what I can see, this is only needed for [Jetpack infinite scroll support](https://github.com/xwp/travel/pull/38/files#diff-4de4ced2b209165dcb7320372c986efaR53). And it looks like AMP [doesn't support infinite scroll yet](https://github.com/ampproject/amphtml/issues/9423).

2018-04-18 01:53 UTC, kienstra commented on .travis.yml
> +  - npm install github:xwp/wp-dev-lib
Is this needed? It seems like Travis checks are running well, and `wp-dev-lib` is added to `devDependencies` in [package.json](https://github.com/xwp/travel/blob/9940a4a5bf88eeae3db9d618b414ba2880dd5384/package.json#L38).

2018-04-18 01:53 UTC, kienstra commented on README.md
> +Travel uses a [Gulp](https://gulpjs.com/) build process to generate and optimize the code for the theme. All development is done in the `/dev` folder and Gulp preprocesses, transpiles, and compiles t
Thanks for adding this "Developing" section. Does this line apply to this theme? It doesn't look like there's a `/dev` directory.

2018-04-18 01:53 UTC, kienstra commented on README.md
> +* Built with [PSTT theme](https://github.com/mor10/pstt)
Maybe this should reflect the new name:
>Built with the WP Rig theme

2018-04-18 01:53 UTC, kienstra commented on css/content.css
> +/*--------------------------------------------------------------
My guess is that we won't use many of the `.css` files in this PR. We'll know more as front-end PRs like #39 progress.

2018-04-18 01:53 UTC, kienstra commented on functions.php
> +function travel_content_width() {
This function is probably not needed.

2018-04-18 01:53 UTC, kienstra commented on functions.php
> +function travel_fonts_url() {
This probably isn't needed. But we'll probably know more as front-end PRs like #39 progress.

2018-04-18 01:53 UTC, kienstra commented on functions.php
> +function travel_widgets_init() {
This probably isn't needed for now, as the [design](https://www.figma.com/file/L14jTE7iNGOE7DH57Ro7ncyu/Travel-Theme) doesn't look to have widget areas.

2018-04-18 01:53 UTC, kienstra commented on inc/template-tags.php
> +function travel_is_amp() {
As I understand it, this is a Native AMP theme, per the [added_theme_support](https://github.com/xwp/travel/blob/c4200803a8407c8db6b25b60fa2f98127adf2ddf/includes/class-amp-travel-theme.php#L73). So this function probably isn't needed, as it will usually be true.

Unless:
```php
is_admin() || is_feed() || ( defined( 'REST_REQUEST' ) && REST_REQUEST )
```
(from [is_amp_endpoint()](https://github.com/Automattic/amp-wp/blob/286381ca5e9b868a220a4c4049ca8fa128dbbd8d/includes/amp-helper-functions.php#L173))

2018-04-18 01:53 UTC, kienstra commented on functions.php
> +function travel_scripts() {
Assuming this is a Native AMP theme, per the [added_theme_support](https://github.com/xwp/travel/blob/c4200803a8407c8db6b25b60fa2f98127adf2ddf/includes/class-amp-travel-theme.php#L73), we probably can't use any of these front-end scripts.

2018-04-18 01:53 UTC, kienstra commented on gulpfile.babel.js
> +/* eslint-env es6 */
Is this file needed?

2018-04-18 01:53 UTC, kienstra commented on inc/jetpack.php
> +	add_theme_support(
It looks like [AMP doesn't support infinite scroll yet](https://github.com/ampproject/amphtml/issues/9423), so maybe we shouldn't `add_theme_support()` for it.

2018-04-18 01:53 UTC, kienstra commented on inc/template-tags.php
> +if ( ! function_exists( 'travel_index_header' ) ) :
I don't think this will be needed, as the header will probably be dictated by the [design](https://www.figma.com/file/L14jTE7iNGOE7DH57Ro7ncyu/Travel-Theme).

2018-04-18 01:53 UTC, kienstra commented on inc/template-tags.php
> +if ( ! function_exists( 'travel_posted_on' ) ) :
We can probably leave these most of these template tags in for now, to allow our templates to use them. But I could later remove any functions we don't use.

2018-04-18 01:53 UTC, kienstra commented on inc/template-tags.php
> +if ( ! function_exists( 'travel_the_attachment_navigation' ) ) :
This probably isn't needed.

2018-04-18 01:53 UTC, kienstra commented on phpcs.xml.dist
> -	<rule ref="WordPress.WP.DeprecatedFunctions">
Is this rule not needed?

2018-04-18 01:53 UTC, kienstra commented on phpcs.xml.dist
> -	<exclude-pattern>*/html/*</exclude-pattern>
Good idea to add this.

2018-04-18 01:53 UTC, kienstra commented on phpcs.xml.dist
> +	<config name="testVersion" value="5.2-99.0"/>
It looks like [travis.yml](https://github.com/xwp/travel/blob/2de9d9519ced48b2c4a13443b41fe00ada02b4f9/.travis.yml#L280) checks for PHP 5.6, 7.0, 7.1, and 7.2. Should this be:
```
value="5.6-99.0"
```

2018-04-18 01:53 UTC, kienstra commented on sidebar.php
> +<?php
It doesn't look like [the design](https://www.figma.com/file/L14jTE7iNGOE7DH57Ro7ncyu/Travel-Theme) has a sidebar, so I don't think we need this file. Still, I'm not sure if there are plans for a sidebar later.

2018-04-18 01:53 UTC, kienstra commented on style.css
> +CSS normalization based in part on normalize.css by
We'll probably have to see how the front-end work goes in PRs like #39. But as our styling is specific to the [design](https://www.figma.com/file/L14jTE7iNGOE7DH57Ro7ncyu/Travel-Theme), we probably won't need a lot of this styling.

2023-01-10 09:37 UTC, closed without merging