[WIP] 59: Update header design and layout
xwp/wp-travel-theme pull request #67
Opened 2018-04-24 11:50 UTC by miina

Fixes #59.
- Uses header with search for archives and adventures post type.
- Adds breadcrumbs to taxonomy page;
- Adds title to search page.

Todo:
- Styling fixes

The search page looks like this:
![screen shot 2018-04-24 at 2 48 18 pm](https://user-images.githubusercontent.com/3294597/39185075-925551c6-47ce-11e8-8691-a8ecb1e9d50a.png)

However, the taxonomy and adventure page look like this and need styling fixes -- for some reason any change made to the adventure.css or archive.css breaks the style, the style fixes are added only to search.css
![screen shot 2018-04-24 at 2 48 03 pm](https://user-images.githubusercontent.com/3294597/39185089-a164fb3a-47ce-11e8-934d-1a6ae49b5da0.png)

2018-04-24 11:53 UTC, miina commented
@kienstra This PR should be ready other than styling issues.

@mehigh Do you think you could review the header, breadcrumbs, and the title's style? The search page needs just a review but adventure and archives page need styling fixes, too -- for some reason here as well as in #64, any change I make to `adventure.css` or `archive.css` breaks the style, would be great if you could help with that.

2018-04-24 16:32 UTC, miina commented
Edit: Looks like `archive.css` looks better after the last change, however, the `adventure.css` is completely stripped if I make any changes, so this still needs some attention. Currently the header looks like this:
![screen shot 2018-04-24 at 7 29 26 pm](https://user-images.githubusercontent.com/3294597/39200844-f4758f84-47f5-11e8-8013-90600100c763.png)

Basically the difference with other pages is missing this:
```
.search-travel-btn,
.search-travel-btn:visited{
    margin-left: 25px;
    color: #8b58e3;
}
.travel-date-input{
    line-height:0.125rem
}
```

Not sure why this breaks the CSS on `adventure.css`.

(cc @mehigh)

2018-04-24 17:50 UTC, kienstra requested changes
**Thanks, A Few Points**

Hi @miina,
Thanks a lot for your work here. This matches the updated [designs](https://www.figma.com/file/L14jTE7iNGOE7DH57Ro7ncyu/Travel-Theme) well, other than the styling issues that you mentioned above.

There are a few points here. But this is almost ready, pending the styling points.

2018-04-24 17:50 UTC, kienstra commented on search.php
> +						<h1><?php printf( '%d Results for <strong>%s</strong>', esc_html( amp_travel_get_posts_count() ), esc_html( $_GET['s'] ) ); ?></h1>
The search template is looking good. How about using `_n()` to differentiate between singular and plural here?

2018-04-24 17:50 UTC, kienstra commented on templates/breadcrumb.php
> +	<span class="bold py1 pl1 pr1"><?php echo esc_html( $term->name ); ?></span>
The breadcrumbs look really good. But I think the second item could be changed:

<img width="1281" alt="breadcrumb-taxonomy" src="https://user-images.githubusercontent.com/4063887/39204150-9ed90850-47bc-11e8-9c43-c24ebcdd317b.png">

2018-04-24 17:50 UTC, kienstra commented on templates/breadcrumb.php
> +	<span class="bold py1 pl1 pr1"><a class="travel-link" href="<?php echo esc_html( home_url() ); ?>"><?php esc_html_e( 'Home' ); ?></a></span>
Could you please change:
```php
esc_html( home_url() )
```
to:
```php
esc_url( home_url() )
```

2018-04-24 17:50 UTC, kienstra commented on archive.php
> +					<div><?php printf( '%d adventures', esc_html( amp_travel_get_posts_count() ) ); ?></div>
How about using `_n()` in case there's only one adventure?

2018-04-25 08:07 UTC, miina commented
@kienstra Thanks for reviewing, the changes are made within 6f5c870.

2018-04-25 11:35 UTC, miina commented
@kienstra and @mehigh Added the missing style change for adventure page as well now, the style just needs reviewing now (and any fixes that Mike might find necessary).

2018-04-25 14:39 UTC, kienstra commented
**Approved, Other Than Styling Issues**

Hi @miina,
Your latest changes look good. As you mentioned, this could still use help with styling. But other than that, it's approved.

2018-04-25 14:40 UTC, kienstra approved these changes

2018-04-25 14:50 UTC, kienstra commented
**Request For Retro Sanity-Check**

@mehigh, if you have time, could you do a quick sanity-check of the styling here? The styling appears well on the `archive.php`, `search.php`, and single adventure pages. 

But otherwise, I think this is ready to merge.

2018-04-25 14:50 UTC, merged

2018-04-25 16:34 UTC, mehigh commented
CSS looks OK, thanks for the work here @miina !