Add star ratings and validate reviews
xwp/wp-travel-theme pull request #75
Opened 2018-05-02 10:31 UTC by DavidCramer

Implements a star rating field based on the example here https://ampbyexample.com/advanced/star_rating/ 

![screen recording 2018-05-02 at 12 27 pm](https://user-images.githubusercontent.com/307466/39518714-59360c6e-4e04-11e8-800a-4021c72f6662.gif)

Fixes #76

2018-05-02 11:02 UTC, DavidCramer commented
@kienstra I think this is done, you can review when you get a chance. thanks.

2018-05-03 03:23 UTC, kienstra requested changes
**Looks Great, A Few Points**

Hi @DavidCramer,
This looks really good, and it'd be a good feature to demo.

There are only 2 requested changes below.

2018-05-03 03:23 UTC, kienstra commented on includes/functions.php
> +	?>
Nice use of the closing `?>` tag to output this markup.

2018-05-03 03:23 UTC, kienstra commented on includes/functions.php
> +function amp_travel_check_first_review( $approved, $comment ) {
Good idea to check that the reviewer hasn't already reviewed it.

2018-05-03 03:23 UTC, kienstra commented on includes/functions.php
> +		return new WP_Error( 'already_reviewed', __( 'A rating is required.' ), 409 );
Should the error be something like `'no_rating'` instead of `'already_reviewed'`? The message of `'A rating is required.'` seems to suggest that there's no rating.

2018-05-03 03:23 UTC, kienstra commented on templates/entry/meta/rating.php
> +		</div>
This looks good!

2018-05-03 03:23 UTC, kienstra commented on includes/functions.php
> +		return new WP_Error( 'already_reviewed', __( 'You may only submit a single review.' ), 409 );
<img width="903" alt="single-adventure-review" src="https://user-images.githubusercontent.com/4063887/39557969-ddf81298-4e50-11e8-8954-99baba1588f6.png">

2018-05-03 03:23 UTC, kienstra commented on includes/functions.php
> +
It's nice how this checks if the user made a comment already. How about something like this, to avoid directly using `$wpdb`?

```php
if ( ! empty( $comment['user_id'] ) ) {
    $author_arg = array(
        'author__in' => array( $comment['user_id'] ),
    );
} elseif ( ! empty( $comment['comment_author_email'] ) ) {
    $author_arg = array(
        'author_email' => $comment['comment_author_email'],
    );
} else {
    return $approved;
}

$comments = get_comments(
    array_merge(
        $author_arg,
        array(
            'post_id' => $comment['comment_post_ID'],
            'status'  => 'approve',
        )
    )
);

if ( ! empty( $comments ) ) {
    return new WP_Error( 'already_reviewed', __( 'You may only submit a single review.', 'travel' ), 409 );
}
```

2018-05-03 03:23 UTC, kienstra commented on includes/functions.php
> +	$approved = amp_travel_check_first_review( $approved, $comment );
It's nice how this decomposes the check into the function `amp_travel_check_first_review`.

2018-05-03 03:24 UTC, kienstra commented on assets/css/adventure.css
> +/*! normalize.css v5.0.0 | MIT License | github.com/necolas/normalize.css */html{font-family:sans-serif;line-height:1.15;-ms-text-size-adjust:100%;-webkit-text-size-adjust:100%}body{margin:0}article,
Could the line with `.travel-results-results-stars-empty-small {` please have an empty line above it?

(for some reason this comment doesn't appear next to the proper line)

2018-05-03 04:46 UTC, DavidCramer commented on includes/functions.php
> +	?>
Smaller and cleaner I think :)

2018-05-03 04:47 UTC, DavidCramer commented on includes/functions.php
> +function amp_travel_check_first_review( $approved, $comment ) {
@kienstra ye, don't want to count each comment as a review. will mess things up. Also, should probably force comments to not be in threaded mode.

2018-05-03 04:48 UTC, DavidCramer commented on includes/functions.php
> +		return new WP_Error( 'already_reviewed', __( 'A rating is required.' ), 409 );
oops! sorry, copy and pasted from the other one. will fix.

2018-05-03 05:19 UTC, DavidCramer commented on includes/functions.php
> +
@kienstra Brilliant thanks! I actually tried to find out how to do that but eventually found this from how it's done in core to find duplicates. Will update!

2018-05-03 05:58 UTC, DavidCramer commented
@kienstra Changes made, feel free to review this when you get a chance.

2018-05-03 14:42 UTC, kienstra commented on assets/css/stars.css
> +.rating {
Great idea to move this into a separate file, to allow enqueuing it in a few places.

2018-05-03 17:06 UTC, kienstra approved these changes
**Approved**

Hi @DavidCramer,
Thanks for for making these changes, and for adding this nice feature for the star rating.

2018-05-03 17:08 UTC, merged