Fix comment form styling
xwp/wp-travel-theme pull request #80
Opened 2018-05-04 18:56 UTC by kienstra

**Request For Review**

As @ThierryA mentioned, there were styling issue on the single 'adventure' page's comment form:
* The "Name" and "Email" should appear next to each other on desktop displays
* There wasn't enough space between some `<label>` and `<input>` elements

https://dev-amp-start-travel.pantheonsite.io/adventure/surfing-day-board-and-wetsuits-included-in-price/

<img width="1205" alt="adventure-page" src="https://user-images.githubusercontent.com/4063887/39646915-a14788d0-4fa2-11e8-9d2d-66155ff21a6b.png">

Here's the display with this PR applied:
<img width="1014" alt="single-adventure-pr-applied" src="https://user-images.githubusercontent.com/4063887/39646973-cc1cf202-4fa2-11e8-94bb-2e7acaa2e05f.png">

2018-05-04 18:59 UTC, kienstra commented on assets/css/adventure.css
> +/*! normalize.css v5.0.0 | MIT License | github.com/necolas/normalize.css */html{font-family:sans-serif;line-height:1.15;-ms-text-size-adjust:100%;-webkit-text-size-adjust:100%}body{margin:0}article,
This diff looks more extensive than it is. I only removed `.comment-form .comment-form-email`
from before the rule:
```css
.comment-form .comment-form-rating{width:100%;padding-right:15px;margin-bottom:-15px;}
```

2018-05-04 19:00 UTC, kienstra commented on assets/css/adventure.css
> +/*! normalize.css v5.0.0 | MIT License | github.com/necolas/normalize.css */html{font-family:sans-serif;line-height:1.15;-ms-text-size-adjust:100%;-webkit-text-size-adjust:100%}body{margin:0}article,
This is simply copied from an earlier version of this file.

2018-05-07 17:01 UTC, DavidCramer commented
Hi @kienstra Just one issue and we're 100's!
![image 2018-05-07 at 6 55 46 pm](https://user-images.githubusercontent.com/307466/39713945-d2e4baec-5228-11e8-855b-55315bd255cc.png)
Easy solution:...
![image 2018-05-07 at 6 57 27 pm](https://user-images.githubusercontent.com/307466/39713982-f0101486-5228-11e8-98af-8eb9b449bd3f.png)

2018-05-07 17:01 UTC, DavidCramer requested changes
Just that email field padding on the right and we're good!

2018-05-07 17:17 UTC, DavidCramer approved these changes

2018-05-07 17:17 UTC, DavidCramer commented
Looks good to me! Thanks @kienstra

2018-05-07 17:29 UTC, kienstra commented
@DavidCramer, thanks for reviewing this!

2018-05-07 17:29 UTC, merged