use select field for ratings if IE11
xwp/wp-travel-theme pull request #81
Opened 2018-05-07 07:37 UTC by DavidCramer

Corrects the star rating on IE11 as mentioned in #8

2018-05-07 07:45 UTC, DavidCramer commented
@kienstra You can give this a test. Thanks.

2018-05-07 21:17 UTC, kienstra requested changes
**Works Well, Very Minor Point**

Hi David,
Thanks for this good solution to IE 11 support. And thanks for reviewing #80 right away, after your workday.

There's a very minor point here.

Ratings on the single 'adventure' page now work on IE 11:
<img width="1290" alt="ie-11-rating" src="https://user-images.githubusercontent.com/4063887/39725633-2025b75a-5212-11e8-80f9-7194385255a9.png">

2018-05-07 21:17 UTC, kienstra commented on includes/functions.php
> +	echo '<p class="comment-form-rating-select"><label for="rating">' . esc_html( 'Your rating' ) . '</label>
Could this be:
```php
esc_html__( 'Your rating', 'travel' )
```

2018-05-08 04:44 UTC, DavidCramer commented
@kienstra Thanks, changes applied and conflicts resolved.

2018-05-08 04:52 UTC, kienstra approved these changes

2018-05-08 04:52 UTC, kienstra commented
Thanks, @DavidCramer! This looks good.

2018-05-08 04:52 UTC, merged